print("Welcome to brand name generator")
country_name=input("What's name of the city you grow up in?")
country_name=country_name.capitalize()
pet_name=input("What'syour pet's name?")
pet_name=pet_name.capitalize()
print("Your brand name could be "+country_name+" "+pet_name)